package com.kbcoding.contactscomposemp.ui.theme

import androidx.compose.material.darkColors
import androidx.compose.material.lightColors


val DarkColorScheme = darkColors(
    primary = GreenPrimaryDark,
    primaryVariant = GreenContainerDark,
    secondary = GreenSecondaryDark,
    secondaryVariant = GreenSecondaryContainerDark,
    background = BackgroundDark,
    surface = SurfaceDark,
    error = ErrorDark,
    onPrimary = OnGreenDark,
    onSecondary = OnGreenSecondaryDark,
    onBackground = OnBackgroundDark,
    onSurface = OnSurfaceDark,
    onError = OnErrorDark,
//    tertiary = GreenTertiaryDark,
//    primaryContainer = GreenContainerDark,
//    onPrimaryContainer = OnGreenContainerDark,
//    secondaryContainer = GreenSecondaryContainerDark,
//    onSecondaryContainer = OnGreenSecondaryContainerDark,
//    onTertiary = OnGreenTertiaryDark,
//    onTertiaryContainer = OnGreenTertiaryContainerDark,
//    tertiaryContainer = GreenTertiaryContainerDark,
//    surfaceVariant = SurfaceVariantDark,
//    onSurfaceVariant = OnSurfaceVariantDark,
//    errorContainer = ErrorContainerDark,
//    onErrorContainer = OnErrorContainerDark,
//    outline = OutlineDark,
)

val LightColorScheme = lightColors(
    primary = GreenPrimaryLight,
    primaryVariant = GreenContainerLight,
    secondary = GreenSecondaryLight,
    secondaryVariant = GreenSecondaryContainerLight,
    background = BackgroundLight,
    surface = SurfaceLight,
    error = ErrorLight,
    onPrimary = OnGreenLight,
    onSecondary = OnGreenSecondaryLight,
    onBackground = OnBackgroundLight,
    onSurface = OnSurfaceLight,
    onError = OnErrorLight,
//    tertiary = GreenTertiaryLight,
//    primaryContainer = GreenContainerLight,
//    onPrimaryContainer = OnGreenContainerLight,
//    secondaryContainer = GreenSecondaryContainerLight,
//    onSecondaryContainer = OnGreenSecondaryContainerLight,
//    onTertiary = OnGreenTertiaryLight,
//    onTertiaryContainer = OnGreenTertiaryContainerLight,
//    tertiaryContainer = GreenTertiaryContainerLight,
//    surfaceVariant = SurfaceVariantLight,
//    onSurfaceVariant = OnSurfaceVariantLight,
//    errorContainer = ErrorContainerLight,
//    onErrorContainer = OnErrorContainerLight,
//    outline = OutlineLight,
)